### ISSUE TITLE
Works for cert install, but then cameras can't connect

### ISSUE THREAD

**Issue by reillychase** [rezitech/letsencrypt-unifi-nvr#1]
Hi thanks for the script,

However, I think some things might have changed since it was written.

The script works and the SSL becomes valid, but then when adopting a camera, it gets stuck during the adoption process.

I believe this is related to some changes in how camera streams are encrypted.

I am trying this guide now:
https://www.john.geek.nz/2018/05/using-letsencrypt-with-ubiquiti-unifi-video-server/

More info:
https://community.ubnt.com/t5/UniFi-Video/Custom-SSL-Certificates-in-3-8-1-and-beyond/m-p/2089043

**Comment by reillychase** [comment]
I see that your last commit was in June 2017, the blog post with changes to SSL was made in October 2017, so more than likely that is the problem

**Comment by travisaustin** [comment]
If you figure out what's up, send a pull request and I'd be happy to incorporate it into the script.

**Comment by reillychase** [comment]
Hey @travisaustin I got it working and we can close this issue. Couple of things I discovered:

1. In order to connect a camera to a remotely located NVR, you have to use the adoption token method:
https://help.ubnt.com/hc/en-us/articles/204975924-UniFi-Video-How-to-Adopt-a-Remote-Camera-that-is-not-Displaying-in-the-NVR
2. My camera had version 3.2 firmware which did not have the option for inputting the token. It would connect but then go to "Upgrading" and become stuck.
In order to fix the problem I downloaded NVR version 3.8.3 locally and was able to use that to adopt the camera normally and then upgrade the firmware.
3. Now with the upgraded firmware I was able to input the adoption token into the camera and connect it to the remotely located NVR

Now it works fine, so none of this was actually related to the script, which still works.

**Comment by travisaustin** [comment]
Awesome, @reillychase. Thanks for following up.
